import Head from 'next/head'
import Image from 'next/image'
import Main from '../components/Main'

export default function Home() {
  return (
    <div className="Home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='home__container'>
        <Main/>
        <div className='home_image'>
        <Image src="/main.svg" width={1024} height={1224} alt="main_svg"/>

        </div>
      </div>

      
    </div>
  )
}
